config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/widget.rb
class Widget < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: %i[ show edit update destroy ]

  # GET /widgets or /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1 or /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets or /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: "Widget was successfully created." }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1 or /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: "Widget was successfully updated." }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1 or /widgets/1.json
  def destroy
    @widget.destroy!

    respond_to do |format|
      format.html { redirect_to widgets_path, status: :see_other, notice: "Widget was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def widget_params
      params.expect(widget: [ :name, :description ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hello Rails8" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/widgets/_form.html.erb
<%= form_with(model: widget) do |form| %>
  <% if widget.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
        <% widget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/widgets/_widget.html.erb
<div id="<%= dom_id widget %>">
  <p>
    <strong>Name:</strong>
    <%= widget.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= widget.description %>
  </p>

</div>

app/views/widgets/edit.html.erb
<% content_for :title, "Editing widget" %>

<h1>Editing widget</h1>

<%= render "form", widget: @widget %>

<br>

<div>
  <%= link_to "Show this widget", @widget %> |
  <%= link_to "Back to widgets", widgets_path %>
</div>

app/views/widgets/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Widgets" %>

<h1>Widgets</h1>

<div id="widgets">
  <% @widgets.each do |widget| %>
    <%= render widget %>
    <p>
      <%= link_to "Show this widget", widget %>
    </p>
  <% end %>
</div>

<%= link_to "New widget", new_widget_path %>

app/views/widgets/new.html.erb
<% content_for :title, "New widget" %>

<h1>New widget</h1>

<%= render "form", widget: @widget %>

<br>

<div>
  <%= link_to "Back to widgets", widgets_path %>
</div>

app/views/widgets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @widget %>

<div>
  <%= link_to "Edit this widget", edit_widget_path(@widget) %> |
  <%= link_to "Back to widgets", widgets_path %>

  <%= button_to "Destroy this widget", @widget, method: :delete %>
</div>